### ISSUE TITLE
How to use it with CLI?

### ISSUE THREAD

**Issue by visualcookie** [lucasmotta/sass-module-importer#10]
Hi,

I'm using basic CLI and want to be able to use it but I don't find any word of it in the README.

**Comment by rafaelrinaldi** [comment]
@visualcookie I just ran into the same problem. It turns out that you can simply do the following:

``` sh
node-sass index.scss bundle.css --importer=node_modules/sass-module-importer
```

It should work (worked for me).

**Comment by ringods** [comment]
@rafaelrinaldi I can't get it to work. I tried passing the importer location using the following cases:
- with the `=` sign between argument and value
- with a space between them
- with `node_modules/sass-module-importer` as the location
- with `node_modules/sass-module-importer/lib` as the location
- with `node_modules/sass-module-importer/lib/index.js` as the location

In all cases, I had a file `bootstrap.scss` containing this to process:

```
@import "bootstrap-sass"
```

**Comment by k0bura** [comment]
I have the same issue. Looks like the module.exports need to be a more specific format for the command line: https://github.com/sass/node-sass#usage-1

**Comment by lucasmotta** [comment]
That's more an issue related to node-sass and its own documentation that is not clear.
