### ISSUE TITLE
Import module partials

### ISSUE THREAD

**Issue by ncoden** [lucasmotta/sass-module-importer#13]
I need a feature : allow to import module partials.

_For example for foundation-sites:_

``` scss
@import
  'foundation-sites/grid/grid',
  'foundation-sites/typography/typography',
  'foundation-sites/forms/forms',
  ...
```

_instead of (without sass-module-importer)_

``` scss
@import
  'bower_components/foundation-sites/scss/grid/grid',
  'bower_components/foundation-sites/scss/typography/typography',
  'bower_components/foundation-sites/scss/forms/forms',
  ...
```

You can search for these files from the path of the main file given by "main" or "style" of package.json/bower.json

_For example, for foundation sites :_

``` json
// bower.json
  ...
  "main": [
    "scss/foundation.scss",
    "dist/foundation.js"
  ],
  ...
```

_-> Search in bower `foundation-sites` component directory + `scss/` and `dist/`_

**Comment by ncoden** [comment]
poke @lucasmotta

**Comment by levithomason** [comment]
I also need this feature.  I would like to transform this:

``` scss
@import "../../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap/variables";
```

into

``` scss
@import "bootstrap-sass/assets/stylesheets/bootstrap/variables";
```

Though, simply checking the `main` key won't work for `bootstrap-sass`.  The main entry is

``` json
{ "main": "assets/javascripts/bootstrap.js" }
```

So, unless it did a recursive search it wouldn't find the import.  I think simply adding `node_modules` and `bower_components` to the search paths is another easy win and would cover my use case.  In fact, I thought that is what this module did!

**Comment by clydin** [comment]
I was able to get this to work by importing the full filename of the partial:
`@import "bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss";`

Adding logic to handle the sass import algorithm would be needed to support partials directly.

**Comment by lucasmotta** [comment]
Hey @ncoden, is this still an issue? The solution that @clydin is the way to go.
I've created #27 that includes a test to cover this problem.

**Comment by ncoden** [comment]
This is still an issue. Thank you.

**Comment by lucasmotta** [comment]
@ncoden are you installing `foundation-sites` through bower or npm?

**Comment by ncoden** [comment]
@lucasmotta Through npm.

**Comment by lucasmotta** [comment]
@ncoden I'm fixing something on my side now, but you will have to open an issue at [zurb/foundation-sites](https://github.com/zurb/foundation-sites) and ask them to include the the `style` field on their package.json:

```
{
  "main": "dist/foundation.js",
  "style": "scss/foundation.scss"
}
```

That will make life easier, but I'm also adding more checks to help this problem. I tested myself now using `foundation-sites` and it did work this time.
