### ISSUE TITLE
Handle arrays in "main:" value of bower.json

### ISSUE THREAD

**Issue by lachieh** [lucasmotta/sass-module-importer#14]
I've been scratching my head for the last 10 minutes trying to work out why this doesn't work with [normalize.scss](https://github.com/JohnAlbin/normalize-scss). Turns out, this particular module has an array as the `main:` file, instead of a string and `.match` doesn't work on arrays.

[This is the line](https://github.com/lucasmotta/sass-module-importer/blob/master/src/index.js#L30) causing the issue is where it fails.

Example from [susy](http://susy.oddbird.net):

```
"main": "sass/_susy.scss",
```

Example from normalize.scss

```
"main": [
    "sass/_normalize.scss"
],
```

I'm using the css library for the moment, but i'd rather the sass version.

**Comment by ringods** [comment]
Bumped into the same thing yesterday evening. `bootstrap-sass` has an array with a JS and a SCSS file in `bower.json`. 

On top of that, it only points to the JS file in the `main` section of the `package.json` file. Which one has precedence?

**Comment by lachieh** [comment]
From what I can tell, it looks like the order is npm first, then bower and then root files. As for the file that it looks at, if the package is installed through bower, it will only look for `bower.json`. This is managed through the [resolve-bower](https://www.npmjs.com/package/resolve-bower) dependancy.

~~While the issue here regarding arrays still needs to be resolved, the `bootstrap-sass` package should really be updated to include the stylesheet in the `main` section of the `bower.json` file.~~

Edit: Just looked at the bower.json file in the [bootstrap-sass](https://github.com/twbs/bootstrap-sass/) repo. Because the `package.json` doesn't list a scss/sass/css file in the main section, it will just skip onto the `bower.json` file which will then trigger this error.
