### ISSUE TITLE
Handle "sass" key in project definitions.

### ISSUE THREAD

**Issue by ghost** [lucasmotta/sass-module-importer#15]
Bootstrap 4, for instance, provides a `style` key (the built CSS file) and a `sass` key (the sass sources). As is, sass-module-importer includes the prebuilt css in this case.

**Comment by LaylBongers** [comment]
I ran into this same issue, bootstrap 4's mixins don't work without an immediate explanation on why because of this.

**Comment by lucasmotta** [comment]
Feature added on 8880db7dabfbd94c40b9922aa93ba6497aaced98
