### ISSUE TITLE
Options to search different file structures or extensions?

### ISSUE THREAD

**Issue by joelataylor** [lucasmotta/sass-module-importer#2]
Hi, I'm certainly new to NPM packages, but I'm noticing that by using sass-module-importer that the file/dir structure has to be pretty specific for the right `*scss` file to be found.

For instance, it looks like the file name must match the import command:
`@import 'bulma';`  =>   `node_modules/bulma/bulma.sass`

but this doesn't work:
`@import 'font-awesome';`  => `node_modules/font-awesome/scss/font-awesome.scss` 
I have to put the full path in.

Another package has a structure like:
`node_modules/sass-spacing/index.scss`
And this also doesn't work unless I put the full path (minus the `node_modules` dir)

Do I misunderstand how this package interacts with `node-sass`? Or could we make it a bit more inclusive for different file/directory structures?

Thanks!!

**Comment by lucasmotta** [comment]
Hey @joelataylor.. When I first wrote this plugin, it was a very naive implementation.
It was not looking for other fields on the package.json other than the `main` field. And also it was not resolving the paths between dependencies.

But I took some time to rewrite the implementation of this plugin to have a better support.
I did a test with "bulma", "font-awesome", "sass-spacing" and they all worked with no problem!

It's worth to say that "font-awesome" [uses the "css" file](https://github.com/FortAwesome/Font-Awesome/blob/master/package.json#L5) and not the "scss". So if you want to overwrite variables, you have to use the SCSS version, which is pretty easy:

``` scss
$fa-css-prefix: new-prefix
@import "font-awesome/scss/font-awesome.scss";
```

I will close this issue for now as I've tested those exactly modules you mentioned, but do let me know if the new version (1.2.0) does not work for you!

**Comment by joelataylor** [comment]
Awesome! Thanks. :+1:
